EGICApps.Web/Controllers/SecurityController.cs
using EGIC.Core.Domain.Users;
using EGIC.Core.Models.Security;
using EGIC.Core.Models.Users;
using Microsoft.AspNetCore.Mvc;
using EGICApps.Services.Authentication;
using System;

namespace EGICApps.Web.Controllers
{
    public class SecurityController : BaseController
    {
        #region Fields

        private readonly IAuthenticationService _authenticationService;

        #endregion

        #region CTOR

        public SecurityController(
            IServiceProvider service,
            IAuthenticationService authenticationService) : base(service)
        {
            _authenticationService = authenticationService;
        }

        #endregion


        #region Actions

        #region Login/Logout

        [Route("/login")]
        public IActionResult Login()
        {
            var model = new LoginModel();
            return View(model);
        }

        [HttpPost]
        [Route("/login")]
        public virtual IActionResult Login(LoginModel model, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                model.Username = model.Username.Trim().ToUpper();
                var loginResult = _authenticationService.ValidateUser(model.Username, model.Password, out User user);
                switch (loginResult)
                {
                    case UserLoginResults.Successful:
                        {


                            //sign in new user
                            _authenticationService.SignIn(user);

                            if (string.IsNullOrEmpty(returnUrl) || !Url.IsLocalUrl(returnUrl))
                                return RedirectToAction("Index", "Home");

                            return Redirect(returnUrl);
                        }
                    case UserLoginResults.UserNotExist:
                        ModelState.AddModelError("", "User not existed");
                        break;
                    case UserLoginResults.Deleted:
                        ModelState.AddModelError("", "User has been deactivated");
                        break;
                    case UserLoginResults.WrongPassword:
                    default:
                        ModelState.AddModelError("", "Wrong password, please make sure your password and try again.");//
                        break;
                }
            }

            return View(model);
        }

        [Route("/logout")]
        public virtual IActionResult Logout()
        {
            //standard logout 
            _authenticationService.SignOut();

            return RedirectToAction("Login");
        }

        #endregion

        public virtual IActionResult AccessDenied(string pageUrl)
        {
            var currentUser = _workContext.CurrentUser;
            return View();
        }

        #endregion
    }
}

EGICApps.Web/Views/Security/AccessDenied.cshtml
<div class="content text-center">
    <div class="content-header">
        <h1>
            Access Denied
        </h1>
    </div>
    <i class="fa fa-minus-circle" style="font-size:260px;color:#e66666;"></i>
    <div class="alert alert-danger alert-dismissable">
        You tried to access unauthorized page.
    </div>
</div>

EGICApps.Web/Views/Security/Login.cshtml
@model LoginModel
@using EGIC.Core.Models.Security
@{
    //Layout = "_AdminLayout";
    Layout = null;// "_AdminLayout";
    string pageTitle = "Login";
    //title
    ViewBag.Title = pageTitle;
}
<!DOCTYPE html>
<html lang="en-us">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>EGIC - Servers & Applications | Login</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/adminLTE/AdminLTE-2.3.0.min.css" />

    <!-- Font Awesome -->
    <link href="~/lib/fontAwesome/css/font-awesome-4.6.3.min.css" rel="stylesheet" />

    <!-- Ionicons -->
    <link href="~/lib/ionicons/ionicons.min.css" rel="stylesheet" />


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <script src="~/lib/jquery-1.10.2.min.js"></script>
    <script src="~/lib/bootstrap/bootstrap.min.js"></script>
</head>
<body>
    <div class="login-box" style="margin: 0 auto 0 auto!important;">
        <div class="login-logo">
            <img src="~/images/egic.jpg" style="width:100%" />
            <div>
                <strong style="color: #725f58!important;">EGIC</strong>
                <small style="color: #f28b2f!important;">Servers & Applications</small>
            </div>
        </div>
        <!-- /.login-logo -->
        <div class="login-box-body">
            <p class="login-box-msg text-center">
                <strong>Servers & Applications</strong>
                <br />
                <br />
                Login
            </p>

            <form asp-action="Login" asp-controller="Security" asp-route-returnurl="@Context.Request.Query["ReturnUrl"]" method="post">
                <p class=" alert-danger" ID="lblErrorMessage" visible="false">
                    <div asp-validation-summary="ModelOnly" class="message-error text-danger"></div>
                </p>
                <div class="form-group has-feedback">
                    <input asp-for="Username" class="form-control" autofocus="autofocus" placeholder="Username" />
                    <span asp-validation-for="Username"></span>
                    <span class="glyphicon glyphicon-user form-control-feedback"></span>
                </div>
                <div class="form-group has-feedback">
                    <input asp-for="Password" class="form-control" placeholder="Password" />
                    <span asp-validation-for="Password"></span>
                    <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                </div>
                <div class="row">
                    <div class="col-xs-4">
                        <input class="btn btn-success btn-block btn-flat" type="submit" value="Login" />
                    </div>
                    <!-- /.col -->
                    <div class="col-xs-8">

                    </div>
                    <!-- /.col -->
                </div>
            </form>

        </div>
        <!-- /.login-box-body -->
    </div>
    <!-- /.login-box -->
</body>
</html>